spring.application.name=projeto_financial_company

server.error.include-stacktrace=never

spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${EMAIL_AUTH_BOOL}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_START_TLS_BOOL}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
